const harryPotterName = [
  'Harry Potter',
  'Voldemort',
  'Hermione',
  'Viktor Krum',
  'Ron Weasely',
  'Ginny',
  'Seamus Finnigan',
  'Dobby',
  'Nymphadora Tonks',
  'Sirius Black',
  'Luna Lovegood',
  'Peter Pettigrew',
  'Moaning Myrtle',
  'Dumbledore',
  'Snape',
  'Draco',
  'Lucius Malfoy',
  'Bellatrix Lestrange',
  'Neville Longbottom',
  'McGonagall',
  'Fleur Delacour',
  'Lily Potter',
  'Professor Flitwick',
  'Alastor Moody',
  'Argus Filch',
  'Trelawney',
  'Rita Skeeter',
  'Cornelius Fudge',
];

export default harryPotterName;
